<template>
  <div>
    <section class="partner-page">
      <div style="max-width: 1400px">
        <h1>Join Us on the Journey to Tomorrow's Wonders Today!</h1>
        <div class="partner-sub-heading">Become a B2pip partner today</div>
        <div class="partner-button mt-4">
          <button @click="scrollToForm">Become a partner</button>
        </div>
      </div>
    </section>
    <section class="partner-sub" style="display: block">
      <div class="partner-subtitle">
        You can get up to 40% of our revenue. You will receive a percentage of
        the money generated by each active client you refer to us. This can
        reach up to 40% on each trade they make.
      </div>
    </section>
    <!-- Feature section -->
    <div class="key-feature">
      <h1>Key Features</h1>
    </div>
    <Features />
    <!-- Feature Section -->
    <StartEarning />
    <FeatureComponent bg-color="black-color" arrow-component="arrow-theme">
      <template #header> Auto pay-outs for partners </template>
      <template #description>
        We pay your profit daily into your account and you can access your money
        instantly, whenever you want.
      </template>
      <template #image>
        <img src="../../assets/img/payouts.png" alt="" class="promo-img m-2" />
      </template>
    </FeatureComponent>
    <InterfaceCarousel />
    <DosDont />
    <div class="practice">
      "In accordance with the Revshare programme introducing brokers get paid
      only for the customer’s trading activity after a broker has already
      received the profit for trading."
    </div>
    <contact-form>
      <template #contact-heading>
        <div class="contact-heading">
          If you haven't found the answer to your question, feel free to contact
          our support.
        </div>
      </template>
    </contact-form>
  </div>
</template>
<script setup>
import { ref } from "vue";
import Icon from "./partials/features/Icon.vue";
import Features from "./partials/features/index.vue";
import StartEarning from "./partials/start-earning/StartEarning.vue";
import DosDont from "./partials/dos/DosDont.vue";
import InterfaceCarousel from "./partials/interfaces/InterfaceCarousel.vue";
import FeatureComponent from "./partials/features/FeatureComponent.vue";
import ContactForm from "../../components/ContactForm.vue";

const form = ref({
  name: "",
  email: "",
  number: "",
  region: "",
  message: "",
  checked: false,
});
const contactForm = ref(null);
function scrollToForm() {
  const el = document.getElementById("contactForm");
  el.scrollIntoView({ behavior: "smooth" });
}
</script>

<style>
.practice {
  font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
    Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
  color: #c9f73a;
  background-color: black;
}
</style>
<style>
.key-feature {
  display: flex;
  justify-content: center;
  top: 244px;
  z-index: 99;
  max-width: 1400px;
}
.key-feature h1 {
  font: 40px/44px "Nekst", sans-serif;
  font-weight: 700;
  padding: 10px;
  background: linear-gradient(to right, #c9f73a 8px, transparent 8px) 0 0,
    linear-gradient(to left, #c9f73a 8px, transparent 8px) 100% 100%,
    linear-gradient(to bottom, #c9f73a 8px, transparent 8px) 0 0,
    linear-gradient(to top, #c9f73a 8px, transparent 8px) 100% 100%;

  background-repeat: no-repeat;
  background-size: 20px 20px;
}
.partner-page {
  top: 100px;
  background: #c9f73a;
  position: relative;
  overflow: hidden;
  height: auto;
  padding: 64px 0 80px;
  text-align: left;
}
.partner-page h1 {
  width: 100%;
  padding-right: 12px;
  padding-left: 12px;
  flex: 0 0 100%;
  max-width: 100%;
  font: 40px/44px "Nekst", sans-serif;
  font-weight: 700;
  margin-bottom: 0;
  position: relative;
  z-index: 2;
}
.partner-sub-heading {
  margin-top: 24px;
  position: relative;
  width: 100%;
  padding-right: 12px;
  padding-left: 12px;
  flex: 0 0 100%;
  max-width: 100%;
  font: 24px/26px "Nekst", sans-serif;
  font-weight: 700;
}
.partner-button {
  position: relative;
  width: 100%;
  padding-right: 12px;
  padding-left: 12px;
  flex: 0 0 100%;
  max-width: 100%;
}
.partner-button button {
  width: 100%;
  border: none;
  color: #000;
  cursor: pointer;
  text-decoration: none;
  transition: all 0.24s;
  opacity: 1;
  width: 100%;
  padding: 16px 40px;
  font: 20px/30px "Inter", sans-serif;
  font-weight: 400;
  background-color: #000;
  color: #fff;
  border: 1px solid transparent;
}
.partner-sub {
  width: 100%;
  bottom: -74px;
  margin-bottom: 90px;
}
.partner-subtitle {
  flex: 0 0 91.66667%;
  max-width: 91.66667%;
  margin-left: 0;
  position: relative;
  width: 100%;
  padding-right: 24px;
  padding-left: 24px;
  font: 24px/30px "Inter", sans-serif;
  font-weight: 600 !important;
  text-align: left;
}
.partner-image {
  width: 120px;
  position: absolute;
  right: 5%;
}
@media (min-width: 768px) {
  .partner-image {
    width: 130px;
    margin-right: 5%;
    position: absolute;
    right: 0;
    top: 52px;
    z-index: 99;
  }
  .partner-button button {
    width: auto;
  }
  .partner-page h1,
  .partner-sub-heading,
  .partner-button {
    flex: 0 0 83.33333%;
    max-width: 83.33333%;
    margin-left: 8.33333%;
  }
  .key-feature h1 {
    font: 56px/62px "Nekst", sans-serif;
    font-weight: 700;
  }
  .partner-page h1 {
    font: 56px/62px "Nekst", sans-serif;
    font-weight: 700;
  }
}
@media (min-width: 1400px) {
  .partner-image {
    width: 220px;
    margin-right: 5%;
    position: absolute;
    right: 0;
    top: 52px;
    z-index: 99;
  }
}
</style>
<style>
@media (770px < width < 1280px) {
  /* Section 1 & 2 */
  /* .partner-page {
    height: 500px;
    margin: 0 32px;
  } */
  .partner-sub {
    width: 100%;
    margin-bottom: 80px;
  }
  .partner-subtitle {
    float: right;
    width: 40%;
    margin-right: 42px;
    font: 22px/24px "Inter", sans-serif;
  }
}
</style>

<style>
@media (min-width: 1280px) {
  /* Section 1 & 2 */
  .partner-page {
    height: 600px;
    margin: 0 64px;
  }
  .partner-page h1 {
    font: 96px/104px "Nekst", sans-serif;
    font-weight: 700;
  }
  .partner-sub-heading {
    margin-top: 40px;
    font: 40px/44px "Nekst", sans-serif;
    font-weight: 700;
  }
  .partner-sub {
    width: 100%;
    margin-bottom: 140px;
  }
  .partner-subtitle {
    float: right;
    width: 29%;
    margin-right: 17%;
    font: 24px/36px "Inter", sans-serif;
    font-weight: 600;
  }
}
</style>

<style>
@media (min-width: 2400px) {
  .partner-image {
    right: 17%;
  }
  .partner-subtitle {
    margin-right: 21%;
  }
}
</style>
